[book]
title = "Construção APIs web com GO"
author = "Gustavo"
language = "pt-BR"
multilingual = true
src = "src"

[build]
build-dir = "book"

[output.html]
default-theme = "Navy"
cache-busting = true
preferred-dark-theme = "Navy"
additional-js = []
git-repository-url = "https://github.com/Gustavo-maia-gst/goworkshop"

[output.html.fold]
enable = true
level = 2
